/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthHandoffRouteImport } from './routes/auth.handoff'
import { Route as ApiVoteRouteImport } from './routes/api.vote'
import { Route as ApiSubscribeRouteImport } from './routes/api.subscribe'
import { Route as ApiFeedbackRouteImport } from './routes/api.feedback'
import { Route as ApiErrorRouteImport } from './routes/api.error'
import { Route as ApiCommentRouteImport } from './routes/api.comment'
import { Route as ApiCacheRouteImport } from './routes/api.cache'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth-session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHandoffRoute = AuthHandoffRouteImport.update({
  id: '/auth/handoff',
  path: '/auth/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoteRoute = ApiVoteRouteImport.update({
  id: '/api/vote',
  path: '/api/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiErrorRoute = ApiErrorRouteImport.update({
  id: '/api/error',
  path: '/api/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentRoute = ApiCommentRouteImport.update({
  id: '/api/comment',
  path: '/api/comment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCacheRoute = ApiCacheRouteImport.update({
  id: '/api/cache',
  path: '/api/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth-session',
  path: '/api/auth-session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth-session': typeof ApiAuthSessionRoute
  '/api/cache': typeof ApiCacheRoute
  '/api/comment': typeof ApiCommentRoute
  '/api/error': typeof ApiErrorRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/vote': typeof ApiVoteRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth-session': typeof ApiAuthSessionRoute
  '/api/cache': typeof ApiCacheRoute
  '/api/comment': typeof ApiCommentRoute
  '/api/error': typeof ApiErrorRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/vote': typeof ApiVoteRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth-session': typeof ApiAuthSessionRoute
  '/api/cache': typeof ApiCacheRoute
  '/api/comment': typeof ApiCommentRoute
  '/api/error': typeof ApiErrorRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/vote': typeof ApiVoteRoute
  '/auth/handoff': typeof AuthHandoffRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth-session'
    | '/api/cache'
    | '/api/comment'
    | '/api/error'
    | '/api/feedback'
    | '/api/subscribe'
    | '/api/vote'
    | '/auth/handoff'
    | '/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth-session'
    | '/api/cache'
    | '/api/comment'
    | '/api/error'
    | '/api/feedback'
    | '/api/subscribe'
    | '/api/vote'
    | '/auth/handoff'
    | '/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/api/auth-session'
    | '/api/cache'
    | '/api/comment'
    | '/api/error'
    | '/api/feedback'
    | '/api/subscribe'
    | '/api/vote'
    | '/auth/handoff'
    | '/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiCacheRoute: typeof ApiCacheRoute
  ApiCommentRoute: typeof ApiCommentRoute
  ApiErrorRoute: typeof ApiErrorRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ApiVoteRoute: typeof ApiVoteRoute
  AuthHandoffRoute: typeof AuthHandoffRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/handoff': {
      id: '/auth/handoff'
      path: '/auth/handoff'
      fullPath: '/auth/handoff'
      preLoaderRoute: typeof AuthHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vote': {
      id: '/api/vote'
      path: '/api/vote'
      fullPath: '/api/vote'
      preLoaderRoute: typeof ApiVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/error': {
      id: '/api/error'
      path: '/api/error'
      fullPath: '/api/error'
      preLoaderRoute: typeof ApiErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment': {
      id: '/api/comment'
      path: '/api/comment'
      fullPath: '/api/comment'
      preLoaderRoute: typeof ApiCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache': {
      id: '/api/cache'
      path: '/api/cache'
      fullPath: '/api/cache'
      preLoaderRoute: typeof ApiCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-session': {
      id: '/api/auth-session'
      path: '/api/auth-session'
      fullPath: '/api/auth-session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiCacheRoute: ApiCacheRoute,
  ApiCommentRoute: ApiCommentRoute,
  ApiErrorRoute: ApiErrorRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ApiVoteRoute: ApiVoteRoute,
  AuthHandoffRoute: AuthHandoffRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
