#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
ENV_FILE="apps/portal/.dev.vars"

banner "Feedbax manual production proof"

stage "Notion CLI: install and authenticate"
say "Use Notion's official CLI for workspace discovery and read-back verification."
if ! command -v ntn >/dev/null 2>&1; then
  step "Install the official Notion CLI after reviewing https://developers.notion.com/cli/get-started/overview."
  confirm "Install ntn from the official ntn.dev installer now?" || { warn "Setup stopped before installation."; exit 1; }
  curl -fsSL https://ntn.dev | bash
fi
ntn --version
step "Authorize the intended Notion Workspace in the browser window."
ntn login

stage "Notion: integration and parent page"
say "Create a dedicated internal integration and grant it access to a test-only parent page."
open_url "https://www.notion.so/profile/integrations"
step "Create an internal integration for the proof with Insert content, Read comments, and Insert comments capabilities."
step "Open the dedicated test parent page, choose Connections, and add the integration."
ask_secret NOTION_TOKEN "Paste the internal integration secret:"
ask NOTION_PARENT_PAGE_ID "Paste the parent page ID from its URL:"
write_env NOTION_TOKEN "$NOTION_TOKEN"
write_env NOTION_PARENT_PAGE_ID "$NOTION_PARENT_PAGE_ID"

stage "Notion: create the canonical Installation"
say "The setup command creates fresh sibling Feedback and Changelog Data Sources and publishes the Feedbax roadmap."
EXISTING_DATA_SOURCE_ID=$(_existing NOTION_FEEDBACK_DATA_SOURCE_ID || true)
if [[ -n "$EXISTING_DATA_SOURCE_ID" ]]; then
  warn "An older Feedback Data Source is configured. It will remain untouched and its local configuration will be backed up."
fi
confirm "Create a fresh Feedbax Database, seed its public roadmap, and switch local configuration after success?" || { warn "Setup stopped before mutation."; exit 1; }
NOTION_TOKEN="$NOTION_TOKEN" pnpm manual:setup:notion "$NOTION_PARENT_PAGE_ID"
step "Open the parent page and confirm the Feedback and Changelog data sources now exist."
pause "Confirmed?"

stage "Notion CLI: read-back verification"
NOTION_FEEDBACK_DATABASE_ID=$(_existing NOTION_FEEDBACK_DATABASE_ID)
NOTION_FEEDBACK_DATA_SOURCE_ID=$(_existing NOTION_FEEDBACK_DATA_SOURCE_ID)
NOTION_CHANGELOG_DATA_SOURCE_ID=$(_existing NOTION_CHANGELOG_DATA_SOURCE_ID)
ntn api "v1/databases/$NOTION_FEEDBACK_DATABASE_ID" >/dev/null
ntn api "v1/data_sources/$NOTION_FEEDBACK_DATA_SOURCE_ID" >/dev/null
ntn api "v1/data_sources/$NOTION_CHANGELOG_DATA_SOURCE_ID" >/dev/null
ROADMAP_JSON=$(ntn datasources query "$NOTION_FEEDBACK_DATA_SOURCE_ID" --limit 20 --json)
if command -v jq >/dev/null 2>&1; then
  ROADMAP_COUNT=$(printf '%s' "$ROADMAP_JSON" | jq '.results | length')
else
  ROADMAP_COUNT=$(printf '%s' "$ROADMAP_JSON" | grep -o '"object":"page"' | wc -l | tr -d ' ')
fi
[[ "$ROADMAP_COUNT" -eq 12 ]] || { warn "Expected 12 seeded roadmap Posts, found $ROADMAP_COUNT."; exit 1; }
say "Verified the database, both data sources, and 12 roadmap Posts through ntn."

stage "Local verification"
say "Verify the repository and Worker bundle before authenticating Cloudflare."
pnpm format:check
pnpm lint
pnpm type-check
pnpm test
pnpm build
pnpm deploy:dry-run
pause "Local verification passed. Press Enter to continue."

stage "Cloudflare: authenticate Wrangler"
open_url "https://dash.cloudflare.com/"
step "Sign in to the Cloudflare account that will own this test Worker."
step "Return here and authorize Wrangler in the browser when prompted."
pnpm --dir apps/portal exec wrangler login
pnpm --dir apps/portal exec wrangler whoami
pause "Wrangler shows the intended Cloudflare account?"

stage "Cloudflare: configure and deploy the Worker"
say "Update the existing feedbax Worker with the complete new Installation contract. Values are never printed."
DEV_VARS="apps/portal/.dev.vars"
required_secret_count=32
configured_secret_count=$(grep -Ec '^(NOTION_TOKEN|NOTION_FEEDBACK_[A-Z_]+|NOTION_CHANGELOG_[A-Z_]+|NOTION_COMMENT_CAPABILITY_PROBE_PAGE_ID|FEEDBAX_API_KEY_HASH|PARTICIPATION_SIGNING_SECRET)=' "$DEV_VARS" || true)
[[ "$configured_secret_count" -eq "$required_secret_count" ]] || {
  warn "Expected $required_secret_count required Worker secrets, found $configured_secret_count. Rerun or recover Notion setup first."
  exit 1
}
while IFS='=' read -r key value; do
  [[ "$key" == "NOTION_TOKEN" || "$key" == NOTION_FEEDBACK_* || "$key" == NOTION_CHANGELOG_* || "$key" == "NOTION_COMMENT_CAPABILITY_PROBE_PAGE_ID" || "$key" == "FEEDBAX_API_KEY_HASH" || "$key" == "PARTICIPATION_SIGNING_SECRET" ]] || continue
  [[ -n "$value" ]] || { warn "Missing $key in $DEV_VARS"; exit 1; }
  printf '%s' "$value" | pnpm --dir apps/portal exec wrangler secret put "$key"
done < "$DEV_VARS"
warn "Turnstile remains disabled for this proof; production must show the weaker-spam-protection warning."
say "Deploy after secret configuration so the final version is the one under test."
pnpm --filter @feedbax/portal run deploy
ask WORKERS_URL "Paste the deployed https://…workers.dev URL:"
write_env FEEDBAX_WORKERS_URL "$WORKERS_URL"
step "Open the health endpoint and confirm it reports healthy."
open_url "${WORKERS_URL%/}/health"
step "Confirm feedback, Post detail, submission, roadmap, voting, Comments, empty Changelog, and health behavior."
open_url "$WORKERS_URL"
pause "The enabled-capability live smoke cycle and Turnstile warning are recorded?"

stage "Production evidence"
say "Record only non-secret results in the proof document. Never paste dashboard logs or .dev.vars contents."
step "Complete the evidence checklist in docs/version-0.2.0-acceptance.md."
step "Confirm private Feedback properties and Notion page bodies do not render publicly."
step "Edit a roadmap Post in Notion and confirm it appears within the two-minute cache window."
pause "Production evidence recorded?"

stage "Local secret cleanup"
say "Retain the configuration backup until the new Worker has passed every smoke check."
confirm "Remove the temporary plaintext FEEDBAX_SMOKE_API_KEY from apps/portal/.dev.vars?" && {
  tmp=$(mktemp)
  grep -v '^FEEDBAX_SMOKE_API_KEY=' apps/portal/.dev.vars > "$tmp" || true
  mv "$tmp" apps/portal/.dev.vars
  chmod 600 apps/portal/.dev.vars
  say "Removed the local plaintext smoke key."
}
note "The older Notion data source was not modified or deleted."
note "Keep the Notion token and deployed secrets only while this Installation is active."

finish
